dist: bionic
language: c
compiler: gcc

matrix:
    - addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
install:
    - cmake --version

script:
    - scripts/test.sh
